### ISSUE TITLE
400 on saving

### ISSUE THREAD

**Issue by makyo** [makyo/polycul.es#29]
When saving a larger polycule, it throws a 400.

**Comment by makyo** [comment]
Appears to be a deployment/apache problem. Going to try redeploying to `bengalensis`.

**Comment by claiire** [comment]
I'm not sure if you re-deployed yet but if you have, this problem still persists

If you haven't, please ignore me! I was just worried that maybe you had and hadn't checked.

**Comment by makyo** [comment]
I have not, I'm sorry! Work ate me :c It's way up there on my list, though. I have editing to do!

**Comment by claiire** [comment]
ok, good luck w/ your lifestuff and things! love the project btw!

**Comment by KoopaKiy** [comment]
Just wanted to let you know that I set up a test environment and it works with the built in flask hosting, so it does definitely look like an apache problem.

**Comment by makyo** [comment]
Yep, I'm working on getting it up on an nginx/uwsgi setup and off Apache.
Aiming to have that done this week!

**Comment by makyo** [comment]
The move has been completed. I'll leave this open a bit longer in case any more issues crop up.

**Comment by makyo** [comment]
Going to call it. Reopen if this reappears!
