### ISSUE TITLE
A name for the preset currently labelled "???"

### ISSUE THREAD

**Issue by excitedleigh** [makyo/polycul.es#49]
There is a preset in the editor which is a quad/cycle but with two corner nodes connected.

Currently it's labelled "???"; I'd like to propose that it be named "Toastie" due to its resemblance to a cheese toastie.

Happy to file a PR to change the label if this is accepted :)

**Comment by makyo** [comment]
Heck YEAH I'm all about this :D :D :D

**Comment by excitedleigh** [comment]
Fixed by #50 :D
