### ISSUE TITLE
Allow view password to be unset

### ISSUE THREAD

**Issue by Supuhstar** [makyo/polycul.es#51]
#13 introduced a way to make a password required to view a polycule, but it didn't introduce a way to undo that.

As a user,
When I create a polycule,
When I erroneously set a view password on that polycule,
I want to be able to un-set the view password from that polycule, so that it no longer has one.

**Comment by TangentFoxy** [comment]
Firefox just entered my password from autocomplete onto my polycule, and because I cannot unset a view password, I basically have to dump it now. :(

In other words, +1 on this issue.

**Comment by Supuhstar** [comment]
Thank you so much, @makyo ! I really appreciate it 💙💙💙
